### ISSUE TITLE
Help with WS-Federation

### ISSUE THREAD

**Issue by blachawk** [fraabye/cg17presentation#1]
Can this package be tweaked for Umbraco 7 to work with WS-Federation?  I'm looking for a guide to connect the two together.  This was one of the closes resources I have found so far.  Any suggestions?

Thanks!

**Comment by fraabye** [comment]
For WS-Fed have a look at my article for last years 24 Days:
https://24days.in/umbraco-cms/2016/authenticating-with-ad-fs-and-identityextensions/
It might be what you are looking for?

**Comment by blachawk** [comment]
Many many thanks for the guide.   I'll give it a go!

**Comment by fraabye** [comment]
You are welcome. Glad if it is a help. Beware that you might run into login issues if token life times differ between AD FS and Umbraco.
